"""replace full_name with first_name and last_name

Revision ID: d8de99f0ddac
Revises: 40dc69134d56
Create Date: 2024-08-17 12:27:20.620017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8de99f0ddac'
down_revision: Union[str, None] = '40dc69134d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
