"""follow up after changes

Revision ID: 3a8d04f624c8
Revises: 50df4961efee
Create Date: 2024-08-20 11:52:13.708656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8d04f624c8'
down_revision = '50df4961efee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###