"""validated data table

Revision ID: 5f77bd0d160a
Revises: b43b4d600b6b
Create Date: 2024-08-20 15:58:55.227870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f77bd0d160a'
down_revision = 'b43b4d600b6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###