"""Generate initial tables

Revision ID: 7c9e335e6df6
Revises: 925f61b1c04f
Create Date: 2024-08-20 14:04:48.674140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9e335e6df6'
down_revision = '925f61b1c04f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###