"""Change file_content to data_content

Revision ID: 7073dd457477
Revises: 7b6f335fe17d
Create Date: 2024-08-05 22:02:57.269738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7073dd457477'
down_revision: Union[str, None] = '7b6f335fe17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imported_data', sa.Column('data_content', sa.LargeBinary(), nullable=True))
    op.alter_column('imported_data', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('imported_data', 'file_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imported_data', sa.Column('file_content', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.alter_column('imported_data', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('imported_data', 'data_content')
    # ### end Alembic commands ###
