"""Change file_content to JSONB

Revision ID: 7b6f335fe17d
Revises: 12aaba051461
Create Date: 2024-08-05 21:24:19.220959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b6f335fe17d'
down_revision: Union[str, None] = '12aaba051461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imported_data', 'file_content',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imported_data', 'file_content',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
